### ISSUE TITLE
Request for Zipping downloaded files 

### ISSUE THREAD

**Issue by Vigneshsam** [jpillora/cloud-torrent#60] opened 2016-07-02 06:18 UTC
Bro,please add "zip" feature as soon as possible.It was very helpful in your first version.Please add zip or rar feature as soon as possible.

**Comment by jpillora** [comment] 2016-07-02 10:18
Duplicate of #33

Very busy atm with work, though I could  make this my work if you can afford 1000USD

**Closed by jpillora** 2016-07-02 10:18 UTC
