### ISSUE TITLE
url problem

### ISSUE THREAD

**Issue by dileepplayer** [jpillora/cloud-torrent#37] opened 2016-02-26 05:16 UTC
when the downloaded folder has a name such as "C# Design Fundamentals"  or something similar with spaces, the folder cannot be accessed, instead it truncates at "C"

**Comment by jpillora** [comment] 2016-02-26 05:17
Duplicate of https://github.com/jpillora/cloud-torrent/issues/32

**Closed by jpillora** 2016-02-26 05:17 UTC

**Comment by dileepplayer** [comment] 2016-02-26 05:18
sorry for that, I should have checked before posting.
