### ISSUE TITLE
Folder download

### ISSUE THREAD

**Issue by qymspace** [jpillora/cloud-torrent#61] opened 2016-07-03 10:40 UTC
Is there a way to download a whole torrent folder rather than several links for the files inside the folder?

**Comment by jpillora** [comment] 2016-07-04 02:14
Yep duplicate of #33 
@PavilionVI I haven't though I'm very busy with work atm and the changes I want to make are quite large, mostly due to #24

**Closed by jpillora** 2016-07-04 02:14 UTC
