### ISSUE TITLE
Disconnected ?

### ISSUE THREAD

**Issue by BloodMan29** [jpillora/cloud-torrent#15] opened 2015-09-26 23:01 UTC
Hi !
When I start the binary, and i try to go on the address.
It's giving me "Disconnected" and I can't do anything :(

Thanks !

**Comment by jpillora** [comment] 2015-09-27 00:07
It's your proxy settings, I've had issues with nginx and haven't had time
to debug

**Comment by BloodMan29** [comment] 2015-09-29 18:35
Ok but the thing is that i don't have any proxies in my home and it's doing the thing even if i run it locally and the server doesn't have proxies as well.

**Comment by jpillora** [comment] 2015-09-29 23:18
Ah that's strange, which browser? Version?

**Comment by BloodMan29** [comment] 2015-09-30 06:09
Browser : Firefox the latest version.
Version of cloud-torrent : 0.8.4 (the latest as well ?)
But i've done some testes and when it is intalled on heroku it's working but if
i download it and tried myself on my computer (local) or on servers (i tried 3
differents servers) don't work

On mer., sept. 30, 2015 at 1:18 AM, Jaime Pillora < notifications@github.com [notifications@github.com] > wrote:
Ah that's strange, which browser? Version?
On Wed, 30 Sep 2015 at 4:35 AM BloodMan29 <notifications@github.com> wrote:

> Ok but the thing is that i don't have any proxies in my home and it's
> doing the thing even if i run it locally and the server doesn't have
> proxies as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jpillora/cloud-torrent/issues/15#issuecomment-144149708>
> .
>
—
Reply to this email directly or view it on GitHub
[https://github.com/jpillora/cloud-torrent/issues/15#issuecomment-144218450] .[https://github.com/notifications/beacon/AHt8PcUtirZ4V1A8Qw5NvzRiGou_9K0Gks5o2xPggaJpZM4GEZLy.gif]

**Comment by jpillora** [comment] 2015-09-30 06:12
Cool found the bug: `Connection: keep-alive, Upgrade` I'm assuming it'll just be `Upgrade`. It'll be working on Heroku because they proxy websockets and would just be setting `Connection: Upgrade`. Will fix soon. thanks for the report.

**Comment by BloodMan29** [comment] 2015-09-30 06:57
Okay thanks !

On mer., sept. 30, 2015 at 8:12 AM, Jaime Pillora < notifications@github.com [notifications@github.com] > wrote:
Cool found the bug: Connection: keep-alive, Upgrade I'm assuming it'll just be Upgrade . It'll be working on Heroku because they proxy websockets and would just be
setting Connection: Upgrade . Will fix soon. thanks for the report.

—
Reply to this email directly or view it on GitHub
[https://github.com/jpillora/cloud-torrent/issues/15#issuecomment-144291930] .[https://github.com/notifications/beacon/AHt8PYybSSNd__ctUmZCcCCHiZt-sXmTks5o23TdgaJpZM4GEZLy.gif]

**Comment by jpillora** [comment] 2015-09-30 19:42
releasing 0.8.5 now, thanks again, this should fix that proxy error i was having too :)

**Comment by Porco-Rosso** [comment] 2015-12-02 15:14
I'm on the newest version, but still have this issue behind nginx. 
Could you maybe share your config?

**Comment by jpillora** [comment] 2015-12-02 20:46
I changed web socket libraries, I think that's the cause, I just haven't
had time to look at it yet

**Comment by jpillora** [comment] 2015-12-05 15:20
Found the issue, separate to last issue. Nginx was failing due to incorrect matching of the `Connection` header. The websockets library is rejecting websockets where the `Host` header doesn't match the `Origin` header. I'm pushing a fix which removes this check. However, it could also be fixed by just ensuring `Host = localhost:<port>` and `Origin = http://localhost:<port>`.

**Closed** 2015-12-05 16:12 UTC

**Comment by Porco-Rosso** [comment] 2015-12-05 17:30
Sorry to reopen, but I've updated to the newest version, and am still having the same problem.
Am I missing something? Are there some lines I should be adding to my Nginx config?

**Comment by jpillora** [comment] 2015-12-05 22:02
No worries, I'm testing with a different proxy, I'll try nginx

**Comment by Porco-Rosso** [comment] 2016-11-14 22:52
Just came back to this, still having the issue and haven't been able to resolve it
Shame cause it looks great running without the reverse proxy
