### ISSUE TITLE
Feature: Download only certain file

### ISSUE THREAD

**Issue by ilbonte** [jpillora/cloud-torrent#21] opened 2015-12-22 10:02 UTC
It is possible to add the option of deselecting unwanted file?

**Comment by jpillora** [comment] 2015-12-22 11:55
I originally had this feature, though the torrent engine (https://github.com/anacrolix/torrent) didn't support stopping specific files so I decided not to include it. I've just raised https://github.com/anacrolix/torrent/issues/48 to see if this is possible.

**Comment by kt1996** [comment] 2016-08-01 12:46
Hey @jpillora any chance this could be implemented soon enough now that feature in anacrolix/torrent (issue 48) appears to be working. It would be awesome and really useful :-D

**Comment by kt1996** [comment] 2016-08-01 14:02
I think this is same as issue 39,....

**Comment by jpillora** [comment] 2016-08-02 01:32
@kt1996 it's definitely supported by anacrolix/torrent, I'm in progress of doing a complete re-architecture of cloud-torrent to support many new features, though it will take some time. Feel free to fork and add it to your own version though :)

Ah yes, it is a duplicate of #39

**Closed by jpillora** 2016-08-02 01:32 UTC
Labels: core-feature

**Comment by poojaearth5** [comment] 2016-08-05 19:37
@jpillora  if possible .. Please add these features also..
1) For adding New torrent  ->  uploading ".torrent" file from pc 
2) Zip [(on-the-fly) or normal Zip with split parts] for torrents with multiple files
3) It will be much better if you can add a file size limit option   (so that after adding new torrent it will first check torrent size and if it less then the max-size-limit then only start downloading )
