### ISSUE TITLE
no zip file

### ISSUE THREAD

**Issue by adiev13** [jpillora/cloud-torrent#66] opened 2016-07-22 06:49 UTC
please add download via zip

**Comment by JetCrusherTorpedo** [comment] 2016-07-23 23:20
![Download zip](https://i.stack.imgur.com/PrvYK.png)

**Comment by PavilionVI** [comment] 2016-07-24 08:35
I think he meant this #33

**Comment by jpillora** [comment] 2016-07-24 13:13
Yep, duplicate of #33

**Closed by jpillora** 2016-07-24 13:13 UTC
